plugins {
    id 'java'
    id 'net.minecraftforge.gradle' version '6.0.51'
}

version = '3.2.4'
group = 'com.github.z80z.lootbeam'
base { archivesName = 'z80z-loot-beam-forge-1.20.1' }

java.toolchain.languageVersion = JavaLanguageVersion.of(17)

minecraft {
    mappings channel: 'official', version: '1.20.1'
    runs {
        client {
            workingDirectory project.file('run')
            mods { z80z_loot_beam { source sourceSets.main } }
        }
    }
}

repositories { mavenCentral() }

dependencies {
    minecraft 'net.minecraftforge:forge:1.20.1-47.4.0'
}

tasks.withType(JavaCompile).configureEach { options.encoding = 'UTF-8' }

processResources {
    def props = [mod_version: project.version]
    inputs.properties props
    filteringCharset = 'UTF-8'
    filesMatching('META-INF/mods.toml') { expand props }
}

jar.finalizedBy('reobfJar')
